### PR TITLE
Update LAB[PL-400]_Lab07_APIs.md

### LINKED ISSUE #118: Minor issue in Lab 7 - missing a curly brace
# Lab 7
#### Step: 5

Description of issue
The code is missing the leading "{" character.   It says:

{webapiurl}}contoso_permits

but should say:

{{webapiurl}}contoso_permits

### PR DESCRIPTION
**Pull request by ephiax20**
Fixes #118 and other minor formatting edits.

### CODE REVIEW

**Comment by julians1966** [comment]
Ellipses is not ellipsis - see https://www.thepunctuationguide.com/ellipses.html

**Comment by ephiax20** [comment]
One ellipsis menu, two ellipses menus, right @julians1966 ?

**Comment by ephiax20** [comment]
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/e/ellipsis-button

**Comment by julians1966** [comment]
OK, understood

**Pull request merged**
