### PR TITLE
Multiple small adjustments

### PR DESCRIPTION
**Pull request by miberr**
Multiple small adjustments

### CODE REVIEW

**Comment by julians1966** [comment]
The change you have made to Lab00_Validate_lab_environment.md cannot be merged as there are different tenants being used for labs; some with Purchase Services and some with Marketplace, some with Power Apps Premium and some with Power Apps Per User
Please create separate PRs for each change

**Comment by julians1966** [comment]
Each exercise in a lab must have steps to open the correct app/component in case the student has to come back and repeat the step. You cannot rely on **No not navtigate away from this page""

**Comment by miberr** [comment]
> Services and some with Marketplace, some with Power Apps Premium and some with Power Apps Per User

Is that old instruction still needed since labs should be  all new tenants and so have the latest changes? Power Apps Per User is not even featured anymore in marketing site

**Comment by miberr** [comment]
> Each exercise in a lab must have steps to open the correct app/component in case the student has to come back and repeat the step. You cannot rely on **No not navigate away from this page""

Added instructions to get back to the app

**Comment by julians1966** [comment]
> > Services and some with Marketplace, some with Power Apps Premium and some with Power Apps Per User
> 
> Is that old instruction still needed since labs should be all new tenants and so have the latest changes? Power Apps Per User is not even featured anymore in marketing site

The labs recycle tenants rather than create new ones, so some students randomly are seeing the old tenant with only the per user option. Eventually these will be updated but it is not safe to remove these instructions at the moment.

**Comment by miberr** [comment]
> > > Services and some with Marketplace, some with Power Apps Premium and some with Power Apps Per User
> > 
> > 
> > Is that old instruction still needed since labs should be all new tenants and so have the latest changes? Power Apps Per User is not even featured anymore in marketing site
> 
> The labs recycle tenants rather than create new ones, so some students randomly are seeing the old tenant with only the per user option. Eventually these will be updated but it is not safe to remove these instructions at the moment.

Okay, removed modifications to that file

**Pull request merged**
